# This is a basic workflow to help you get started with Actions

name: integration-oks

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      vm ip address:
        description: VM ip address
        type: choice
        required: false
        default: 20.243.20.231
        options: 
        -VM2: 48.218.145.192
        -VM3: 20.115.48.84
        -VM1: 20.243.20.231
      env files:
        description: choose the env
        type: choice
        required: false
        options: tilt/hirano_demo.env
                 tilt/hirano_qa.env
                 tilt/hlj.env
                 tilt/hlj_100bots.env
                 tilt/nippan.env
                 tilt/pco.env
                 tilt/qa_map.env
      box numbers:
        description: Box count
        type: number
        required: false
        default: 10

  workflow_call:
    inputs:
      vm ip address:
        description: VM ip address
        type: choice
        required: false
        default: 20.243.20.231
      env files:
        description: choose the env
        type: choice
        required: false
      box numbers:
        description: Box count
        type: number
        required: false
        default: 10     

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  setup_and_run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup and Execute Bash Script
      run: |
        echo "Running bash script with the following parameters:"
        echo "VM IP Address: ${{ inputs.vm_ip_address }}"
        echo "Environment File: ${{ inputs.env_file }}"
        echo "Box Count: ${{ inputs.box_count }}"

        # Execute your bash script with the provided inputs
        ./run_remote.sh --env ${{ inputs.env_file }} --bin-count ${{ inputs.box_count }}

  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Runs a single command using the runners shell
      - name: Run a one-line script
        run: echo Hello, world!

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          echo Add other actions to build,
          echo test, and deploy your project.
